// Code generated by gen_proto.sh.
// DO NOT EDIT!
package main

var Code = map[string]int16{
	"heart_beat_req":     2000, // 心跳包
	"user_login_req":     2001, // 登陆
	"error_ack":          2002, // 错误返回
	"licensing_card_req": 2003, // 发牌请求
}

var RCode = map[int16]string{
	2000: "heart_beat_req",     // 心跳包
	2001: "user_login_req",     // 登陆
	2002: "error_ack",          // 错误返回
	2003: "licensing_card_req", // 发牌请求
}
