// Code generated by gen_proto.sh.
// DO NOT EDIT!
using UnityEngine;
using System;
using System.Collections.Generic;

namespace NetProto.Api
{
    public enum ENetMsgId
    { 
        heart_beat_req = 2000, // 心跳包
        user_login_req = 2001, // 登陆
        error_ack = 2002, // 错误返回
        licensing_card_req = 2003, // 发牌请求
    };
}
