// Code generated by gen_proto.sh.
// DO NOT EDIT!
using UnityEngine;
using System;
using System.Collections.Generic;

namespace NetProto.Proto
{
    public abstract class NetBase
    {
        public short NetMsgId;
        public abstract void Pack(ByteArray w);
    }

    public class null_struct : NetBase
    { 

        public override void Pack(ByteArray w)
        { 
        }

        public static null_struct UnPack(ByteArray reader)
        {
            null_struct tbl = new null_struct();

            return tbl;
        }
    }

    public class byte_id : NetBase
    { 
        public byte id;

        public override void Pack(ByteArray w)
        { 
            w.WriteUnsignedInt8(this.id);
        }

        public static byte_id UnPack(ByteArray reader)
        {
            byte_id tbl = new byte_id();
            tbl.id = reader.ReadUnsignedInt8();

            return tbl;
        }
    }

    public class auto_id : NetBase
    { 
        public Int32 id;

        public override void Pack(ByteArray w)
        { 
            w.WriteInt32(this.id);
        }

        public static auto_id UnPack(ByteArray reader)
        {
            auto_id tbl = new auto_id();
            tbl.id = reader.ReadInt32();

            return tbl;
        }
    }

    public class entity_id : NetBase
    { 
        public UInt64 id;

        public override void Pack(ByteArray w)
        { 
            w.WriteUnsignedInt64(this.id);
        }

        public static entity_id UnPack(ByteArray reader)
        {
            entity_id tbl = new entity_id();
            tbl.id = reader.ReadUnsignedInt64();

            return tbl;
        }
    }

    public class item_id : NetBase
    { 
        public UInt32 id;

        public override void Pack(ByteArray w)
        { 
            w.WriteUnsignedInt(this.id);
        }

        public static item_id UnPack(ByteArray reader)
        {
            item_id tbl = new item_id();
            tbl.id = reader.ReadUnsignedInt32();

            return tbl;
        }
    }
}
