// Code generated by gen_proto.sh.
// DO NOT EDIT!
using UnityEngine;
using System;
using System.Collections.Generic;

namespace NetProto.Proto
{
    public abstract class NetBase
    {
        public short NetMsgId;
        public abstract void Pack(ByteArray w);
    }

    public class null_struct : NetBase
    { 

        public override void Pack(ByteArray w)
        { 
        }

        public static null_struct UnPack(ByteArray reader)
        {
            null_struct tbl = new null_struct();

            return tbl;
        }
    }

    public class byte_id : NetBase
    { 
        public byte id;

        public override void Pack(ByteArray w)
        { 
            w.WriteUnsignedInt8(this.id);
        }

        public static byte_id UnPack(ByteArray reader)
        {
            byte_id tbl = new byte_id();
            tbl.id = reader.ReadUnsignedInt8();

            return tbl;
        }
    }

    public class auto_id : NetBase
    { 
        public Int32 id;

        public override void Pack(ByteArray w)
        { 
            w.WriteInt32(this.id);
        }

        public static auto_id UnPack(ByteArray reader)
        {
            auto_id tbl = new auto_id();
            tbl.id = reader.ReadInt32();

            return tbl;
        }
    }

    public class entity_id : NetBase
    { 
        public UInt64 id;

        public override void Pack(ByteArray w)
        { 
            w.WriteUnsignedInt64(this.id);
        }

        public static entity_id UnPack(ByteArray reader)
        {
            entity_id tbl = new entity_id();
            tbl.id = reader.ReadUnsignedInt64();

            return tbl;
        }
    }

    public class item_id : NetBase
    { 
        public UInt32 id;

        public override void Pack(ByteArray w)
        { 
            w.WriteUnsignedInt(this.id);
        }

        public static item_id UnPack(ByteArray reader)
        {
            item_id tbl = new item_id();
            tbl.id = reader.ReadUnsignedInt32();

            return tbl;
        }
    }

    public class player_cards : NetBase
    { 
        public UInt16[] player_1;
        public UInt16[] player_2;
        public UInt16[] plyaer_3;

        public override void Pack(ByteArray w)
        { 
            w.WriteUnsignedInt16((UInt16)this.player_1.Length);
            for (int k = 0; k < this.player_1.Length; k++)
            { 
                w.WriteUnsignedInt16(this.player_1[k]);
            }
            w.WriteUnsignedInt16((UInt16)this.player_2.Length);
            for (int k = 0; k < this.player_2.Length; k++)
            { 
                w.WriteUnsignedInt16(this.player_2[k]);
            }
            w.WriteUnsignedInt16((UInt16)this.plyaer_3.Length);
            for (int k = 0; k < this.plyaer_3.Length; k++)
            { 
                w.WriteUnsignedInt16(this.plyaer_3[k]);
            }
        }

        public static player_cards UnPack(ByteArray reader)
        {
            player_cards tbl = new player_cards();
            {
                UInt16 narr = reader.ReadUnsignedInt16();
                
                tbl.player_1 = new UInt16[narr];
                
                for (int i = 0; i < narr; i++)
                {
                    tbl.player_1[i] = reader.ReadUnsignedInt16();
                }
            }
            {
                UInt16 narr = reader.ReadUnsignedInt16();
                
                tbl.player_2 = new UInt16[narr];
                
                for (int i = 0; i < narr; i++)
                {
                    tbl.player_2[i] = reader.ReadUnsignedInt16();
                }
            }
            {
                UInt16 narr = reader.ReadUnsignedInt16();
                
                tbl.plyaer_3 = new UInt16[narr];
                
                for (int i = 0; i < narr; i++)
                {
                    tbl.plyaer_3[i] = reader.ReadUnsignedInt16();
                }
            }

            return tbl;
        }
    }
}
